#!/usr/bin/env python3
"""Stage 0c: copy code/decks/configs/data into the report (ASCII-sanitised) and generate
appendices/A_runs_table.tex (run catalogue longtable) and appendices/D_hashes_table.tex (re-verified hashes)."""
from __future__ import annotations
import csv, hashlib, re, shutil
from datetime import datetime, timezone
from pathlib import Path

REPORT = Path(__file__).resolve().parents[1]; PKG = REPORT.parent; ANA = PKG / 'analysis_2026-09-25'
UMAP = {'−': '-', '–': '--', '—': '---', '×': 'x', '≈': '~', 'µ': 'u', 'μ': 'u', '→': '->', '←': '<-',
        '≤': '<=', '≥': '>=', '²': '^2', '³': '^3', '⁰': '^0', '¹': '^1', '⁻': '^-', '‘': "'", '’': "'",
        '“': '"', '”': '"', '°': 'deg', 'Δ': 'Delta', 'ε': 'eps', 'χ': 'chi', 'σ': 'sigma', 'θ': 'theta',
        '±': '+/-', '…': '...', 'Å': 'A', '√': 'sqrt', '·': '*', ' ': ' ', ' ': ' ', 'π': 'pi', 'ℏ': 'hbar'}
sanitised = []

def ascii_copy(src: Path, dst: Path):
    t = src.read_text(encoding='utf-8', errors='replace')
    if any(ord(c) > 127 for c in t):
        t2 = ''.join(UMAP.get(c, c if ord(c) < 128 else '?') for c in t); sanitised.append(str(dst.relative_to(REPORT)))
    else: t2 = t
    dst.parent.mkdir(parents=True, exist_ok=True); dst.write_text(t2, encoding='ascii', newline='\n')

def copies():
    for f in sorted((PKG / 'scripts').glob('*.py')): ascii_copy(f, REPORT / 'code' / 'scripts' / f.name)
    for f in sorted(ANA.glob('scratch/*/*.py')): ascii_copy(f, REPORT / 'code' / 'analysis' / f'{f.parent.name}_{f.name}')
    for f in sorted(list((PKG / 'config').glob('*.yaml')) + list((PKG / 'config').glob('campaign_*.json'))): ascii_copy(f, REPORT / 'code' / 'config' / f.name)
    decks = {'0038': 'final_2p0nm_dos384', '0039': 'final_6p3nm_tuned_dos384', '0040': 'final_13p2nm_dos384', '0014': 'validation_6p3nm_shared',
             '0015': 'tuned_6p3nm_dos96', '0030': 'hyp_backsurface_charge', '0034': 'hyp_no_confinement', '0037': 'B0_repartition',
             '0052': 'C1_nearEc_band', '0041': 'pred_idvd_2p0nm', '0045': 'pred_T358K_2p0nm'}
    for rid, name in decks.items():
        d = next((PKG / 'results' / 'runs').glob(f'run_{rid}_*')); ascii_copy(d / 'device.in', REPORT / 'code' / 'decks' / f'run_{rid}_{name}.in')
    dd = REPORT / 'data'; dd.mkdir(exist_ok=True)
    for f in [PKG / 'data' / 'experimental_clean.csv', PKG / 'data' / 'data_summary.json', PKG / 'results' / 'RUN_INDEX.csv', PKG / 'results' / 'BEST_RUNS_V1.json',
              ANA / 'predictions_canonical.csv', ANA / 'PREDICTIONS_REGISTER.md'] + sorted((PKG / 'results' / 'campaigns').glob('*.json')):
        shutil.copy2(f, dd / f.name)
    shutil.copy2(REPORT / 'digest' / 'runs.csv', dd / 'runs_catalogue.csv')

def tex(s): return str(s).replace('\\', '/').replace('_', '\\_').replace('%', '\\%').replace('&', '\\&').replace('#', '\\#')
def f3(x, fmt):
    try: return fmt.format(float(x))
    except (TypeError, ValueError): return '--'

def run_table():
    rows = list(csv.DictReader((REPORT / 'digest' / 'runs.csv').open(encoding='utf-8')))
    L = ['% generated by tools/make_appendix_assets.py from digest/runs.csv (execution.json + comparison.csv of each run); do not edit by hand',
         '{\\scriptsize\\setlength{\\tabcolsep}{2.5pt}',
         '\\begin{longtable}{@{}l r p{3.3cm} p{2.3cm} r r r r r r r@{}}',
         '\\caption{Catalogue of all V1 ATLAS launches and the measured references. $\\SSfix{-11}{-10}$: fixed-current slope between $10^{-11}$ and $10^{-10}$\\Aum{} (mV/dec); RMSE: active-region log10 error (dec). Metrics of elevated-temperature runs are compared with the 300\\,K data only for reference.}\\label{tab:run-catalogue}\\\\',
         '\\toprule run & $t$ (nm) & label & category & $\\Vthcc$ (V) & $\\Vthlin$ (V) & $\\SSfix{-11}{-10}$ & $\\SScc$ & $\\muFE$ & $\\Ion$ (A/$\\mu$m) & RMSE \\\\ \\midrule \\endfirsthead',
         '\\toprule run & $t$ (nm) & label & category & $\\Vthcc$ & $\\Vthlin$ & $\\SSfix{-11}{-10}$ & $\\SScc$ & $\\muFE$ & $\\Ion$ & RMSE \\\\ \\midrule \\endhead',
         '\\bottomrule \\endfoot']
    for r in rows:
        rid = r['run_id'].replace('run_', '')
        L.append(' & '.join([('\\run{' + rid + '}') if r['run_id'].startswith('run_') else tex(r['run_id']), f3(r['film_nm'], '{:g}'), tex(r['label']), tex(r['category']),
                              f3(r.get('Vth_cc_V'), '{:.3f}'), f3(r.get('Vth_lin_V'), '{:.3f}'), f3(r.get('SS_1e-11_1e-10'), '{:.1f}'), f3(r.get('SS_cc_mVdec'), '{:.1f}'),
                              f3(r.get('mu_FE_cm2Vs'), '{:.2f}'), f3(r.get('Ion_A_um'), '{:.3g}'), f3(r.get('active_rmse_dec'), '{:.3f}')]) + ' \\\\')
        if r.get('note'): L.append('\\multicolumn{11}{@{}l}{\\hspace{1em}\\textit{' + tex(r['note']) + '}} \\\\')
    L += ['\\end{longtable}}']
    (REPORT / 'appendices' / 'A_runs_table.tex').write_text('\n'.join(L) + '\n', encoding='ascii')
    return len(rows)

def hash_table():
    reg = (ANA / 'PREDICTIONS_REGISTER.md').read_text(encoding='utf-8')
    pairs = re.findall(r'\|\s*`([^`]+)`\s*\|\s*`([0-9a-f]{64})`\s*\|', reg)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'); ok = 0
    L = ['% generated by tools/make_appendix_assets.py: SHA-256 re-computed at ' + now,
         '{\\scriptsize\\begin{longtable}{@{}p{8.2cm} p{5.6cm} l@{}}',
         '\\caption{Files of the prediction register with their SHA-256 as registered on 2026-09-24T23:24:53Z (UTC) and re-verified at ' + now + '.}\\label{tab:register-hashes}\\\\',
         '\\toprule file (relative to the package root) & SHA-256 (first 32 hex) & re-check \\\\ \\midrule \\endfirsthead \\toprule file & SHA-256 & re-check \\\\ \\midrule \\endhead \\bottomrule \\endfoot']
    for f, h in pairs:
        p = PKG / f; cur = hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else 'missing'; st = 'identical' if cur == h else ('MISSING' if cur == 'missing' else 'CHANGED'); ok += st == 'identical'
        L.append(f'\\file{{{f}}} & \\texttt{{{h[:32]}}} & {st} \\\\')
    L.append('\\end{longtable}}')
    (REPORT / 'appendices' / 'D_hashes_table.tex').write_text('\n'.join(L) + '\n', encoding='ascii')
    return ok, len(pairs)

if __name__ == '__main__':
    (REPORT / 'appendices').mkdir(exist_ok=True)
    copies(); n = run_table(); ok, tot = hash_table()
    print('run table rows', n, '| register hashes identical', ok, '/', tot, '| ASCII-sanitised copies:', sanitised)
