#!/usr/bin/env python3
"""POST HOC, DESCRIPTIVE: the current range in which measured and TCAD SS agree, per film, found by one rule applied
identically to all films (not a validation, not the reported SS):
  - one-decade windows slid in 0.25-decade steps;
  - admissible if the lower edge >= 10 x the measured floor and the upper edge <= 1e-9 A/um (threshold level);
  - agreeing if |SS_TCAD - SS_meas| <= 5 mV/dec;
  - agreement range = the longest contiguous run of agreeing windows.
Over that range: two-point SS (end crossings) and least-squares SS through all measured points inside, the same for TCAD
(native points inside), and the number of measured points. Output: AGREEMENT_WINDOWS.md (+ printed)."""
import math
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import extraction as ex  # noqa: E402
import run_extraction as rx  # noqa: E402

TOL, STEP = 5.0, 0.25
meas = rx.load_measured()


def fit_ss(vg, i, lo, hi):
    m = (i >= lo) & (i <= hi)
    if m.sum() < 3:
        return None, int(m.sum())
    s = np.polyfit(vg[m], np.log10(i[m]), 1)[0]
    return 1e3 / s, int(m.sum())


L = ['# Post hoc agreement ranges of SS (descriptive; generated by agreement_windows.py)', '',
     f'Rule, applied identically to every film: one-decade windows in {STEP}-decade steps, admissible if the lower edge is '
     f'>= 10 x the measured floor and the upper edge <= 1e-9 A/um; agreeing if |SS_TCAD - SS_meas| <= {TOL:.0f} mV/dec; the '
     'longest contiguous run of agreeing windows gives the range. Chosen after seeing the data: it describes where the model '
     'agrees and is not a test or the reported SS (the reported SS is the on-current-normalised window).', '',
     '| film | agreement range (A/um) | decades | V_G range (V) | measured points | SS two-point meas / TCAD | SS fit meas / TCAD | max abs Delta in the windows |',
     '|---|---|---|---|---|---|---|---|']
for t in rx.FILMS:
    vg, i = meas[t]; tc = rx.load_tcad(t); fl = ex.off_floor(vg, i)
    wins = []
    for e in np.arange(-14.0, -8.99, STEP):
        lo, hi = 10 ** e, 10 ** (e + 1)
        if lo < 10 * fl or hi > 1.0001e-9:
            continue
        mm = ex.ss_window(vg, i, lo, hi, False); ss = ex.ss_window(tc['vg'], tc['i'], lo, hi, True)
        if mm['ss'] is None or ss['ss'] is None:
            continue
        wins.append((e, ss['ss'] - mm['ss']))
    best, cur = [], []
    for e, d in wins:
        if abs(d) <= TOL and (not cur or abs(e - cur[-1][0] - STEP) < 1e-9):
            cur.append((e, d))
        elif abs(d) <= TOL:
            cur = [(e, d)]
        else:
            cur = []
        if len(cur) > len(best):
            best = list(cur)
    if not best:
        L.append(f'| {t:.1f} nm | none in the admissible range ({10 * fl:.1e} to 1e-9 A/um, '
                 f'{math.log10(1e-9 / (10 * fl)):.1f} dec) | - | - | - | - | - | min |Delta| = {min(abs(d) for _, d in wins):.1f} |')
        continue
    lo, hi = 10 ** best[0][0], 10 ** (best[-1][0] + 1)
    m2 = ex.ss_window(vg, i, lo, hi, False); s2 = ex.ss_window(tc['vg'], tc['i'], lo, hi, True)
    fm, nm = fit_ss(vg, i, lo, hi); fs, _ = fit_ss(tc['vg'], tc['i'], lo, hi)
    L.append(f"| {t:.1f} nm | {lo:.2e} - {hi:.2e} | {math.log10(hi / lo):.2f} | {m2['lo']['v']:.2f} - {m2['hi']['v']:.2f} | {nm} | "
             f"{m2['ss']:.1f} / {s2['ss']:.1f} | {fm:.1f} / {fs:.1f} | {max(abs(d) for _, d in best):.1f} |")
(HERE / 'AGREEMENT_WINDOWS.md').write_text('\n'.join(L) + '\n', encoding='utf-8')
print('\n'.join(L))
