#!/usr/bin/env python3
"""POST HOC, DESCRIPTIVE: the current range in which measured and TCAD SS agree, per film, by one rule applied
identically to all films (not a validation and not the reported SS). Two variants of the measured curve:
  raw            : measured I_D;   windows admissible if lower edge >= 10 x floor;
  floor removed  : I_D - floor;    windows admissible if lower edge >= 1 x floor (below it the difference is noise).
Common: one-decade windows slid in 0.25-decade steps, upper edge <= 1e-9 A/um; agreeing if |SS_TCAD - SS_meas| <= 5
mV/dec; agreement range = the longest contiguous run of agreeing windows (ties: more measured points, then lower current).
Over the range: two-point SS, least-squares SS through the measured points inside, and the number of points.
Output: AGREEMENT_WINDOWS.md, agreement_windows.json (+ printed). The figure is agreement_windows_figure.py."""
import json
import math
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import extraction as ex  # noqa: E402
import run_extraction as rx  # noqa: E402

TOL, STEP = 5.0, 0.25
VARIANTS = {'raw': 10.0, 'floor removed': 1.0}      # minimum lower edge in units of the floor


def fit_ss(vg, i, lo, hi):
    m = (i >= lo) & (i <= hi)
    if m.sum() < 3:
        return None, int(m.sum())
    return 1e3 / np.polyfit(vg[m], np.log10(i[m]), 1)[0], int(m.sum())


def analyse(t, variant):
    vg, i0 = rx.load_measured()[t]; tc = rx.load_tcad(t); fl = ex.off_floor(vg, i0)
    i = i0 - fl if variant == 'floor removed' else i0
    wins = []
    for e in np.arange(-14.0, -8.99, STEP):
        lo, hi = 10 ** e, 10 ** (e + 1)
        if lo < VARIANTS[variant] * fl * (1 - 1e-9) or hi > 1.0001e-9:
            continue
        mm = ex.ss_window(vg, i, lo, hi, False); ss = ex.ss_window(tc['vg'], tc['i'], lo, hi, True)
        if mm['ss'] is None or ss['ss'] is None:
            continue
        wins.append((float(e), ss['ss'] - mm['ss']))
    runs, cur = [], []
    for e, d in wins:
        if abs(d) <= TOL:
            cur = cur + [(e, d)] if cur and abs(e - cur[-1][0] - STEP) < 1e-9 else [(e, d)]
            runs.append(list(cur))
        else:
            cur = []
    npts = lambda run: int(((i >= 10 ** run[0][0]) & (i <= 10 ** (run[-1][0] + 1))).sum())
    # longest run; ties broken by the number of measured points inside, then by the lower current range
    best = max(runs, key=lambda run: (len(run), npts(run), -run[0][0])) if runs else []
    out = dict(film=t, variant=variant, floor=fl, windows=wins, admissible_from=VARIANTS[variant] * fl)
    if not best:
        return out
    lo, hi = 10 ** best[0][0], 10 ** (best[-1][0] + 1)
    m2 = ex.ss_window(vg, i, lo, hi, False); s2 = ex.ss_window(tc['vg'], tc['i'], lo, hi, True)
    fm, nm = fit_ss(vg, i, lo, hi); fs, _ = fit_ss(tc['vg'], tc['i'], lo, hi)
    out.update(lo=lo, hi=hi, decades=math.log10(hi / lo), vg=[m2['lo']['v'], m2['hi']['v']], n_points=nm, ss_meas=m2['ss'],
               sig_meas=m2['sig'], ss_tcad=s2['ss'], fit_meas=fm, fit_tcad=fs, max_abs_delta=max(abs(d) for _, d in best))
    return out


if __name__ == '__main__':
    res = [analyse(t, v) for v in VARIANTS for t in rx.FILMS]
    (HERE / 'agreement_windows.json').write_text(json.dumps(res, indent=1, default=float))
    L = ['# Post hoc agreement ranges of SS (descriptive; generated by agreement_windows.py)', '',
         f'Rule, identical for every film: one-decade windows in {STEP}-decade steps, upper edge <= 1e-9 A/um; agreeing if '
         f'|SS_TCAD - SS_meas| <= {TOL:.0f} mV/dec; the longest contiguous run gives the range (ties: more measured points, then lower current). Measured curve raw (windows from '
         '10 x floor) or with the floor subtracted (windows from 1 x floor; assumes an additive, gate-independent floor). Chosen '
         'after seeing the data: describes where the model agrees; not a test and not the reported SS.', '',
         '| film | measured curve | agreement range (A/um) | decades | V_G (V) | points | SS two-point meas / TCAD | SS fit meas / TCAD | max abs Delta |',
         '|---|---|---|---|---|---|---|---|---|']
    for r in res:
        if 'lo' not in r:
            L.append(f"| {r['film']:.1f} nm | {r['variant']} | none (admissible from {r['admissible_from']:.1e}; "
                     f"min abs Delta {min(abs(d) for _, d in r['windows']):.1f}) | - | - | - | - | - | - |")
        else:
            fit = (f"{r['fit_meas']:.1f} / {r['fit_tcad']:.1f}" if r['fit_meas'] is not None and r['fit_tcad'] is not None
                   else 'fewer than 3 points')
            L.append(f"| {r['film']:.1f} nm | {r['variant']} | {r['lo']:.2e} - {r['hi']:.2e} | {r['decades']:.2f} | {r['vg'][0]:.2f} - "
                     f"{r['vg'][1]:.2f} | {r['n_points']} | {r['ss_meas']:.1f} ± {r['sig_meas']:.1f} / {r['ss_tcad']:.1f} | "
                     f"{fit} | {r['max_abs_delta']:.1f} |")
    (HERE / 'AGREEMENT_WINDOWS.md').write_text('\n'.join(L) + '\n', encoding='utf-8')
    print('\n'.join(L))
