#!/usr/bin/env python3
"""PROTOCOL.md amendment A1: subthreshold swing in an on-current-normalised window, measured vs TCAD.
Window [r, 10 r] x I_on with r = 10 x max(floor / I_on) over the films (the deepest decade >= 10 x floor everywhere).
Sensitivity (a): normalisation by I_on / (3 V - V_th,cc); (b) window shifted by +0.25 decade.
Outputs: results_a1.json, A1_RESULTS.md, figures/fig4_ss_normalised.(png|pdf).
"""
import json
import math
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(PKG / 'report_latex_full' / 'figures' / 'src'))
import extraction as ex  # noqa: E402
import run_extraction as rx  # noqa: E402
from style import plt, FILM, panel_label  # noqa: E402

MEAS = rx.load_measured()
TC = {t: rx.load_tcad(t) for t in rx.FILMS}
info = {}
for t in rx.FILMS:
    vg, i = MEAS[t]
    vcc = ex.crossing(vg, i, rx.I_CC, False)['v']
    info[t] = dict(floor=ex.off_floor(vg, i), ion=float(i[-1]), ion_tcad=float(TC[t]['i'][-1]), vcc=vcc)
    info[t]['scale_a'] = info[t]['ion'] / (3.0 - vcc)


def windows(key):
    r = 10 * max(info[t]['floor'] / info[t][key] for t in rx.FILMS)
    return r, {t: (r * info[t][key], 10 * r * info[t][key]) for t in rx.FILMS}


r_main, w_main = windows('ion')
r_a, w_a = windows('scale_a')
w_b = {t: (lo * 10 ** 0.25, hi * 10 ** 0.25) for t, (lo, hi) in w_main.items()}
out = dict(rule='PROTOCOL.md amendment A1 (commit 7ce7116)', r_main=r_main, r_a=r_a, films={})
rows = []
for t in rx.FILMS:
    vg, i = MEAS[t]; tc = TC[t]
    res = {}
    for lab, w in (('main', w_main[t]), ('a: I_on/(3 V - V_th,cc)', w_a[t]), ('b: +0.25 dec', w_b[t])):
        m = ex.ss_window(vg, i, *w, False)
        s = ex.ss_window(tc['vg'], tc['i'], *w, True)
        d = s['ss'] - m['ss']; sd = math.hypot(m['sig'], s['sig'])
        adm = dict(lower_over_floor=w[0] / info[t]['floor'], upper_below_threshold_level=bool(w[1] < rx.I_CC),
                   crossings_meas=[m['lo']['n_cross'], m['hi']['n_cross']], crossings_tcad=[s['lo']['n_cross'], s['hi']['n_cross']])
        res[lab] = dict(window=w, measured=m['ss'], sig_measured=m['sig'], tcad=s['ss'], sig_tcad=s['sig'], delta=d, sig_delta=sd,
                        verdict='consistent' if abs(d) <= 2 * sd else 'differs', admissibility=adm,
                        vg_meas=[m['lo']['v'], m['hi']['v']], vg_tcad=[s['lo']['v'], s['hi']['v']])
        rows.append((t, lab, w, m['ss'], m['sig'], s['ss'], s['sig'], d, sd, res[lab]['verdict'], adm))
    out['films'][str(t)] = dict(info=info[t], results=res)
(HERE / 'results_a1.json').write_text(json.dumps(out, indent=1, default=float))

L = ['# Amendment A1: SS in an on-current-normalised window (generated by amendment_a1.py)', '',
     f'Main rule: window [r, 10 r] x I_on, r = {r_main:.3e}. Sensitivity (a): [r, 10 r] x I_on/(3 V - V_th,cc), r = {r_a:.3e} V. '
     'Sensitivity (b): main window x 10^0.25.', '',
     '| film | variant | window (A/um) | lower edge / floor | upper < 1e-9 | SS measured | SS TCAD | Delta | verdict |', '|---|---|---|---|---|---|---|---|---|']
for t, lab, w, mv, ms, sv, ss, d, sd, v, adm in rows:
    L.append(f"| {t} nm | {lab} | {w[0]:.2e} - {w[1]:.2e} | {adm['lower_over_floor']:.1f} | {'yes' if adm['upper_below_threshold_level'] else 'NO'} | "
             f"{mv:.1f} ± {ms:.1f} | {sv:.1f} ± {ss:.1f} | {d:+.1f} ± {sd:.1f} | {v} |")
(HERE / 'A1_RESULTS.md').write_text('\n'.join(L) + '\n', encoding='utf-8')
print('\n'.join(L))

# ---- figure: local SS against absolute and against normalised current; SS vs thickness
fig, ax = plt.subplots(1, 3, figsize=(7.2, 2.55), gridspec_kw=dict(wspace=0.42))
a, b, c = ax
a.axvspan(*rx.WIN, color='#DCE6F2', lw=0)
lo_n, hi_n = r_main, 10 * r_main
b.axvspan(lo_n, hi_n, color='#DCE6F2', lw=0)
for t in rx.FILMS:
    vg, i = MEAS[t]; tc = TC[t]; col = FILM[t]; fl = info[t]['floor']; ion = info[t]['ion']
    x, y = ex.local_ss(vg, i); k = x > 3 * fl
    xs, ys = ex.local_ss(tc['vg'], tc['i']); ks = xs > 1e-15
    a.semilogx(x[k], y[k], 'o', ms=2.6, mfc='none', mec=col, mew=0.7, label=f'{t:.1f} nm')
    b.semilogx(x[k] / ion, y[k], 'o', ms=2.6, mfc='none', mec=col, mew=0.7)
    b.semilogx(xs[ks] / ion, ys[ks], '-', color=col, lw=1.2)
for p in (a, b):
    p.axhline(ex.S_TH, color='0.55', lw=0.7, ls='--'); p.set_ylim(40, 320); p.set_ylabel('local SS (mV/dec)')
a.set_xlim(1e-14, 1e-8); a.set_xlabel('$I_D$ (A/$\\mu$m)')
a.legend(loc='upper left', fontsize=6.2, frameon=True, framealpha=0.95, edgecolor='0.75', title='measured', title_fontsize=6.2)
a.text(0.97, 0.13, 'shaded: fixed window', transform=a.transAxes, ha='right', fontsize=6.0, color='0.3')
b.set_xlim(1e-8, 1e-2); b.set_xlabel('$I_D/I_{on}$')
b.text(0.03, 0.95, 'circles: measured\nlines: TCAD\nshaded: normalised window', transform=b.transAxes, va='top', fontsize=6.0, color='0.3')
tt = np.array(rx.FILMS)
for key, mk, ls, fill, lab in (('measured', 'o', '-', True, 'measured'), ('tcad', 's', '--', False, 'TCAD')):
    v = [out['films'][str(x)]['results']['main'][key] for x in rx.FILMS]
    e = [out['films'][str(x)]['results']['main']['sig_' + key] for x in rx.FILMS]
    c.errorbar(tt, v, yerr=e, fmt=mk + ls, color='#0072B2', ms=4 if fill else 5, mfc=None if fill else 'none', mew=1.0, lw=1,
               capsize=2, label=f'{lab}, normalised window')
R0 = json.loads((HERE / 'results.json').read_text())
vfix = [R0['films'][str(x)]['measured']['ss']['ss'] for x in rx.FILMS]
c.plot(tt, vfix, 'o:', color='0.55', ms=3, lw=0.8, label='measured, fixed window')
c.set_xticks(rx.FILMS); c.set_xlabel('IWO thickness (nm)'); c.set_ylabel('SS (mV/dec)'); c.set_ylim(80, 200)
c.legend(loc='lower left', fontsize=5.6, frameon=True, framealpha=0.95, edgecolor='0.75')
for p, s in zip(ax, 'abc'):
    panel_label(p, s, x=-0.27, y=1.03)
fig.savefig(HERE / 'figures' / 'fig4_ss_normalised.pdf'); fig.savefig(HERE / 'figures' / 'fig4_ss_normalised.png', dpi=300)
print('saved fig4_ss_normalised')
