#!/usr/bin/env python3
"""Markdown tables (RESULTS_TABLES.md) and a workbook (results.xlsx) generated from results.json and the CSV files,
so that no number in the write-up is transcribed by hand."""
import csv
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
R = json.loads((HERE / 'results.json').read_text())
FILMS = ('2.0', '6.3', '13.2')
VGS = ('1.0', '1.5', '2.0', '2.5', '3.0')
pm = lambda v, s, n=3: f'{v:.{n}f} ± {s:.{n}f}'


def verdict(d, s):
    return 'consistent' if abs(d) <= 2 * s else 'differs'


L = ['# Result tables (generated by make_tables.py from results.json; do not edit by hand)', '',
     'Delta = TCAD - measured. Verdict: consistent if |Delta| <= 2 sigma_Delta (PROTOCOL 3.5). Uncertainties are 1 sigma.', '']

L += ['## Table 1. Threshold voltage (V)', '',
      '| film | V_th,cc at 1e-9 A/um, measured | TCAD | Delta (mV) | verdict | TCAD status | V_th,cc at 5e-10 A/um, meas. / TCAD |',
      '|---|---|---|---|---|---|---|']
for t in FILMS:
    m, s = R['films'][t]['measured'], R['films'][t]['simulated']
    a, b = m['vth_cc'], s['vth_cc']
    d = b['v'] - a['v']; sd = (a['sig'] ** 2 + b['sig'] ** 2) ** 0.5
    L.append(f"| {t} nm | {pm(a['v'], a['sig'])} | {pm(b['v'], b['sig'])} | {1e3 * d:+.1f} ± {1e3 * sd:.1f} | {verdict(d, sd)} | fitted (Q_f) | "
             f"{m['vth_cc_10nA']['v']:.3f} / {s['vth_cc_10nA']['v']:.3f} |")
L += ['', '| film | V_T power-law GCA, meas. | TCAD | V_th,ELR (-V_D/2), meas. | TCAD | V_G* meas. / TCAD (V) | ELR flags |',
      '|---|---|---|---|---|---|---|']
for t in FILMS:
    m, s = R['films'][t]['measured'], R['films'][t]['simulated']
    fl = lambda e: ', '.join(x for x, on in (('sweep-limited', e['sweep_limited']), ('not linear', not e['linear_regime'])) if on) or 'ok'
    L.append(f"| {t} nm | {pm(m['pl']['vt'], m['pl']['tot_vt'], 2)} | {pm(s['pl']['vt'], s['pl']['tot_vt'], 2)} | "
             f"{pm(m['elr']['v'], m['elr']['sig'])} | {pm(s['elr']['v'], s['elr']['sig'])} | {m['elr']['vg_star']:.2f} / {s['elr']['vg_star']:.2f} | "
             f"{fl(m['elr'])} / {fl(s['elr'])} |")

L += ['', '## Table 2. Subthreshold swing, window 5e-11 to 5e-10 A/um (mV/dec)', '',
      '| film | measured floor (A/um) | I_lo / floor | meas., raw | meas., primary | TCAD | Delta | verdict | TCAD status | N_SS meas. / TCAD (1e12 cm-2 eV-1) |',
      '|---|---|---|---|---|---|---|---|---|---|']
status = {'2.0': 'fitted (W_TA, N_t)', '6.3': 'not fitted', '13.2': 'not fitted'}
for t in FILMS:
    f = R['films'][t]; m, s = f['measured']['ss'], f['simulated']['ss']
    d = s['ss'] - m['ss']; sd = (m['sig'] ** 2 + s['sig'] ** 2) ** 0.5
    nss = lambda x: (x / R['constants']['S_th_mV_dec'] - 1) * R['constants']['Cox_F_cm2'] / 1.602176634e-19 / 1e12
    prim = 'floor-corrected ' if m['primary'] != 'raw' else ''
    L.append(f"| {t} nm | {f['floor']:.2e} | {m['floor_ratio']:.1f} | {pm(m['raw']['ss'], m['raw']['sig'], 1)} | {prim}{pm(m['ss'], m['sig'], 1)} | "
             f"{pm(s['ss'], s['sig'], 1)} | {d:+.1f} ± {sd:.1f} | {verdict(d, sd)} | {status[t]} | {nss(m['ss']):.2f} / {nss(s['ss']):.2f} |")
L += ['', 'Robustness: Delta for windows shifted by -0.25 / 0 / +0.25 decade (same admissibility rule per window):', '']
for t in FILMS:
    f = R['films'][t]; parts = []
    for k, (a, b) in (('-0.25 dec', (f['measured']['ss_shifted']['-0.25 dec'], f['simulated']['ss_shifted']['-0.25 dec'])),
                      ('0', (f['measured']['ss'], f['simulated']['ss'])),
                      ('+0.25 dec', (f['measured']['ss_shifted']['+0.25 dec'], f['simulated']['ss_shifted']['+0.25 dec']))):
        d = b['ss'] - a['ss']; sd = (a['sig'] ** 2 + b['sig'] ** 2) ** 0.5
        parts.append(f'{k}: {d:+.1f} ± {sd:.1f}')
    L.append(f'- {t} nm: ' + '; '.join(parts) + ' mV/dec')

L += ['', '## Table 3. Field-effect mobility mu_FE = L g_m / (W C_ox V_D) at V_D = 0.7 V (cm2/Vs)', '',
      '| film | V_G (V) | measured | TCAD | Delta | verdict | measured V_G - V_T >= V_D (power-law V_T) |', '|---|---|---|---|---|---|---|']
for t in FILMS:
    m, s = R['films'][t]['measured'], R['films'][t]['simulated']
    for v in VGS:
        a, b = m['mu_fe'][v], s['mu_fe'][v]
        d = b['mu_fe'] - a['mu_fe']; sd = (a['sig'] ** 2 + b['sig'] ** 2) ** 0.5
        L.append(f"| {t} nm | {v} | {pm(a['mu_fe'], a['sig'], 2)} | {pm(b['mu_fe'], b['sig'], 2)} | {d:+.2f} ± {sd:.2f} | {verdict(d, sd)} | "
                 f"{'yes' if m['mu_ch'][v]['linear_regime'] else 'no'} |")
L += ['', 'TCAD free-electron mobility in the solver (mu_band x R(t), constant): ' +
      ', '.join(f"{t} nm {R['films'][t]['tcad']['mu_n']:.2f}" for t in FILMS) + ' cm2/Vs.', '']

L += ['## Table 4. Power-law gradual-channel fit over V_G = 1.0-3.0 V', '',
      '| film | source | V_T (V) | mu_0 (cm2/Vs) | gamma | corr(V_T, gamma) | log10 RMS | adequate (RMS <= 0.01) |', '|---|---|---|---|---|---|---|---|']
for t in FILMS:
    for src, lab in (('measured', 'measured'), ('simulated', 'TCAD')):
        p = R['films'][t][src]['pl']
        L.append(f"| {t} nm | {lab} | {pm(p['vt'], p['tot_vt'], 2)} | {pm(p['mu0'], p['tot_mu0'], 1)} | {pm(p['gamma'], p['tot_gamma'], 2)} | "
                 f"{p['corr_vt_gamma']:+.2f} | {p['rms_log10']:.4f} | {'yes' if p['rms_log10'] <= 0.01 else 'NO'} |")
L += ['', 'Paired fit-range differences TCAD - measured (post hoc; same fit range for both):', '']
for t in FILMS:
    pp = R['films'][t]['paired_powerlaw']
    L.append(f"- {t} nm: gamma {pp['gamma']['delta']:+.2f} (ranges 1.25-3 / 1.5-3 / 1.0-2.5 V: "
             + ' / '.join(f'{x:+.2f}' for x in pp['gamma']['delta_alt_ranges'])
             + f"); V_T {pp['vt']['delta']:+.3f} V (" + ' / '.join(f'{x:+.3f}' for x in pp['vt']['delta_alt_ranges']) + ')')
L += ['', '| film | V_G (V) | mu_ch measured | mu_ch TCAD | TCAD mu_ch / mu_n |', '|---|---|---|---|---|']
for t in FILMS:
    m, s = R['films'][t]['measured'], R['films'][t]['simulated']; mun = R['films'][t]['tcad']['mu_n']
    for v in VGS:
        a, b = m['mu_ch'][v], s['mu_ch'][v]
        L.append(f"| {t} nm | {v} | {pm(a['mu_ch'], a['sig'], 2)} | {pm(b['mu_ch'], b['sig'], 2)} | {b['mu_ch'] / mun:.2f} |")
# ---- derivative check of the power-law fit (added after the first write-up): does the fitted model reproduce the
# slope g_m of the data, not only the current? mu_FE of the model vs mu_FE of the data, and mu_FE / mu_ch
import sys  # noqa: E402
import numpy as np  # noqa: E402
sys.path.insert(0, str(HERE))
import extraction as ex  # noqa: E402
import run_extraction as rx  # noqa: E402
MEAS = rx.load_measured()
L += ['', '## Table 5. Derivative check of the power-law fit (1.0-3.0 V)', '',
      'The fit minimises the error in log10 I_D; this table shows how well the fitted model also reproduces the slope g_m.', '',
      '| film | source | V_G (V) | I_D model / data | mu_FE model | mu_FE data | mu_ch | mu_FE data / mu_ch |', '|---|---|---|---|---|---|---|---|']
for t in rx.FILMS:
    for src, lab in (('measured', 'measured'), ('simulated', 'TCAD')):
        p = R['films'][str(t)][src]['pl']
        if src == 'measured':
            vg, i = MEAS[t]
        else:
            d = rx.load_tcad(t); vg, i = d['vg_m'], d['i_m']
        mfe = ex.MU_FACTOR * ex.gm(vg, i)
        for v in (1.0, 1.5, 2.0, 2.5, 3.0):
            k = int(np.argmin(abs(vg - v))); u = v - p['vt']; g = p['gamma']
            i_mod = float(ex.pl_current(np.array([v]), p['vt'], p['mu0'], g)[0])
            mfe_mod = p['mu0'] * (u ** (g + 1) - max(u - ex.VD, 0.0) ** (g + 1)) / ex.VD
            much = p['mu0'] * u ** g
            L.append(f'| {t} nm | {lab} | {v:.1f} | {i_mod / i[k]:.3f} | {mfe_mod:.2f} | {mfe[k]:.2f} | {much:.2f} | {mfe[k] / much:.2f} |')

# ---- effect of deviations D1-D3 on the verdicts: protocol-as-written uncertainties vs the final ones
SIM_SIG_V, SIM_SIG_SS = 1.5e-3, 1.0


def cross_sig_protocol(c):
    return ((c['sigma_log10_quadratic_retired'] * c['slope_V_per_dec']) ** 2 + c['sig_interp'] ** 2) ** 0.5


def ss_sig_protocol(e):
    blk = e['corrected'] if e['primary'] != 'raw' else e['raw']
    dec = __import__('math').log10(e['window'][1] / e['window'][0])
    s = ((1e3 * ((blk['lo']['sigma_log10_quadratic_retired'] * blk['lo']['slope_V_per_dec']) ** 2
                 + (blk['hi']['sigma_log10_quadratic_retired'] * blk['hi']['slope_V_per_dec']) ** 2) ** 0.5 / dec) ** 2
         + (blk['ss'] - blk['ss_pchip']) ** 2) ** 0.5
    return s


changes = []
for t in FILMS:
    m, s = R['films'][t]['measured'], R['films'][t]['simulated']
    items = [(f'V_th,cc at {lev}', m[k]['v'], cross_sig_protocol(m[k]), m[k]['sig'], s[k]['v'], s[k]['sig'])
             for k, lev in (('vth_cc', '1e-9'), ('vth_cc_10nA', '5e-10'))]
    items.append(('SS window', m['ss']['ss'], ss_sig_protocol(m['ss']), m['ss']['sig'], s['ss']['ss'], s['ss']['sig']))
    for k in ('-0.25 dec', '+0.25 dec'):
        e = m['ss_shifted'][k]
        items.append((f'SS window {k}', e['ss'], ss_sig_protocol(e), e['sig'], s['ss_shifted'][k]['ss'], s['ss_shifted'][k]['sig']))
    for v in VGS:
        a = m['mu_fe'][v]
        items.append((f'mu_FE at {v} V', a['mu_fe'], a['sig_global_protocol'], a['sig'], s['mu_fe'][v]['mu_fe'], s['mu_fe'][v]['sig']))
    items.append(('V_th,ELR (protocol gave no sigma; first run used 1.5 mV)', m['elr']['v'], SIM_SIG_V, m['elr']['sig'], s['elr']['v'], s['elr']['sig']))
    for name, mv, s_prot, s_fin, sv, ss in items:
        d = sv - mv
        sp = (s_prot ** 2 + (SIM_SIG_V if 'ELR' in name else ss) ** 2) ** 0.5
        sf = (s_fin ** 2 + ss ** 2) ** 0.5
        if verdict(d, sp) != verdict(d, sf):
            changes.append(f'- {t} nm, {name}: Delta {d:+.4g}; protocol-as-written ± {sp:.2g} ({verdict(d, sp)}) -> final ± {sf:.2g} ({verdict(d, sf)})')
L += ['', '## Effect of deviations D1-D3 on the verdicts', '',
      'Rows whose verdict differs between the uncertainty estimators written in the protocol and the final, validated ones:', '']
L += changes or ['- none']
(HERE / 'RESULTS_TABLES.md').write_text('\n'.join(L) + '\n', encoding='utf-8')
print('\n'.join(L))

import pandas as pd  # noqa: E402

with pd.ExcelWriter(HERE / 'results.xlsx', engine='xlsxwriter') as xw:
    pd.read_csv(HERE / 'results_table.csv').to_excel(xw, sheet_name='comparison', index=False)
    pd.read_csv(HERE / 'mobility_vs_vg.csv').to_excel(xw, sheet_name='mobility_vs_vg', index=False)
print('written results.xlsx')
